"""migração inicial

Revision ID: 8d24077fb845
Revises: 96c84c34c664
Create Date: 2026-05-18 23:59:52.843255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d24077fb845'
down_revision: Union[str, Sequence[str], None] = '96c84c34c664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.String(), nullable=False),
    sa.Column('build', sa.Integer(), nullable=False),
    sa.Column('obrigatoria', sa.Boolean(), nullable=True),
    sa.Column('apk_url', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_versions_id'), 'app_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_versions_id'), table_name='app_versions')
    op.drop_table('app_versions')
    # ### end Alembic commands ###
