"""expande dados institucionais

Revision ID: 96c84c34c664
Revises: 
Create Date: 2026-05-18 00:22:06.865096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c84c34c664'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=20), nullable=False),
    sa.Column('suap_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email_pessoal', sa.String(length=150), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('senha_hash', sa.String(), nullable=True),
    sa.Column('perfil', sa.Enum('estudante', 'professor', 'tae', 'responsavel', 'externo', name='perfil_usuario'), nullable=False),
    sa.Column('tipo_login', sa.Enum('suap', 'cpf', name='tipo_login_usuario'), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('sincronizado_em', sa.DateTime(), nullable=True),
    sa.Column('ultima_atualizacao', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email_pessoal'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('suap_id')
    )
    op.create_table('credenciais_suap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('usuario_suap', sa.String(length=30), nullable=False),
    sa.Column('credenciais_validas', sa.Boolean(), nullable=True),
    sa.Column('erro_autenticacao', sa.Boolean(), nullable=True),
    sa.Column('senha_suap_criptografada', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('expiracao_token', sa.DateTime(), nullable=True),
    sa.Column('ultimo_login_suap', sa.DateTime(), nullable=True),
    sa.Column('sincronizado_em', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('usuarios_estudantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('email_institucional', sa.String(), nullable=True),
    sa.Column('curso', sa.String(), nullable=True),
    sa.Column('matriz', sa.String(), nullable=True),
    sa.Column('ira', sa.String(), nullable=True),
    sa.Column('ano_ingresso', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_institucional'),
    sa.UniqueConstraint('matricula'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('usuarios_externos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('interesse', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('usuarios_professores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('email_institucional', sa.String(), nullable=True),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('setor', sa.String(), nullable=True),
    sa.Column('campus', sa.String(), nullable=True),
    sa.Column('area_atuacao', sa.String(), nullable=True),
    sa.Column('nucleo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_institucional'),
    sa.UniqueConstraint('matricula'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('usuarios_responsaveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('codigo_responsavel', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('usuarios_tae',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('email_institucional', sa.String(), nullable=True),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('setor', sa.String(), nullable=True),
    sa.Column('campus', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_institucional'),
    sa.UniqueConstraint('matricula'),
    sa.UniqueConstraint('usuario_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios_tae')
    op.drop_table('usuarios_responsaveis')
    op.drop_table('usuarios_professores')
    op.drop_table('usuarios_externos')
    op.drop_table('usuarios_estudantes')
    op.drop_table('credenciais_suap')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
