"""cria app_versions

Revision ID: b08c672a1ddd
Revises: 8d24077fb845
Create Date: 2026-05-20 19:53:44.281982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b08c672a1ddd'
down_revision: Union[str, Sequence[str], None] = '8d24077fb845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('app_versions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('versao', sa.String(), nullable=True),
                    sa.Column('build',sa.Integer(),nullable=False),
                    sa.Column('obrigatoria', sa.Boolean(), nullable=True),
                    sa.Column('apk_url', sa.String(), nullable=False),
                    sa.Column('descricao', sa.String(), nullable=True),
                    sa.Column('ativa', sa.Boolean(), nullable=True),
                    sa.Column('criada_em', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(
        'app_versions'
    )
    # ### end Alembic commands ###
